{% set name = "cubedsphere" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cubedsphere-{{ version }}.tar.gz
  sha256: 4a86e8fe6ad90dc4ba1ec6905e1c949c494bf5324e54bc81ce65829a308ce3bc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - esmpy
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - xesmf
    - xgcm ==0.5.2
    - xmitgcm
    - xarray
    - f90nml
    - numba

test:
  imports:
    - cubedsphere
    - cubedsphere.exorad
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AaronDavidSchneider/cubedsphere
  summary: Library for post processing of MITgcm cubed sphere data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDavidSchneider
